// <auto-generated />
namespace Village_Project_MVC_LinqToSQL_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddResident : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddResident));
        
        string IMigrationMetadata.Id
        {
            get { return "202201190816303_AddResident"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
